### ISSUE TITLE
[proposal] Separate drivers from main project due to dependency issues

### ISSUE THREAD

**Issue by lotodore** [faabiosr/cachego#12]
I'm using this project as simple client side file cache, and it works like a charm. Thanks for providing this library.

I was willing to commit the changes which integrated cachego and noted a large number of new dependencies, including e.g. redis library. These dependencies are added to go.sum and also present in `go list -m all`, which means they are really used. For me this is kind of bad, because I do not want to use any of the other drivers. I'm only using the `cachego.Cache` interface and the file driver.

Since I cannot create new projects in a pull request, I cannot propose a specific solution for this dependency issue. But maybe you could consider that instead of subdirectories, the drivers could be placed in separate projects, so that it is really optional to load them?

This would also be a lot better from a security perspective, as static code analysis may cause alerts of unused libraries.

**Comment by lotodore** [comment]
Moving the drivers would result in incompatible api, so I understand it is not a good idea. I switched to https://github.com/alecthomas/localcache which is probably a better idea if only file cache is needed. Thanks for consideration.

**Comment by faabiosr** [comment]
I am a little late, however as you mentioned it is difficult to move the packages right now. Also I am glad that you shared your thoughts about it and solved by using a different project. I will think how can I move foward with the project regarging this improvement.

Best.
